<<<<<<< HEAD

=======
>>>>>>> 3216e2ba5729a6379c419587e372836d36f4e675
site_name: Technology Innovation Center - CoMakeIT
theme:
  name: material
  custom_dir: theme

<<<<<<< HEAD
  

=======
>>>>>>> 3216e2ba5729a6379c419587e372836d36f4e675
  font:
    # text: Roboto Mono
    text: Roboto
  features:
    - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
<<<<<<< HEAD

    - header.autohide

=======
    - header.autohide
#   language: en
>>>>>>> 3216e2ba5729a6379c419587e372836d36f4e675
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name:  Switch to light mode    
      primary: dark blue
      accent: dark blue
nav:
  # - Home: index.md
  
  - Introduction:
    - Our Products: index.md
  - Developer's Guide:
    - Developers's Guide/Concept.md
    - Generating-WDA:
      - Building WDA: Developers's Guide/Generating-WDA/buildingWDA.md
    - Generating-WDI:
      - Building WDI: Developers's Guide/Generating-WDI/buildingWDI.md
  - Documentation:
    - Basic Concept: Documentation/concept.md
    - WDA:
      - WDA: Documentation/WDA/1.1wda.md
      - Prerequisites: Documentation/WDA/1Preq.md
      - Application: Documentation/WDA/3Application.md
      - Deployment : Documentation/WDA/4Deployment.md
      - Communication : Documentation/WDA/5communication.md
    - WDI:
      - WDI: Documentation/WDI/1WDI.md
      - Prerequisites: Documentation/WDI/2Prerequisites.md
<<<<<<< HEAD
=======
# extra:
#   announcement: |
#     {% include "announcement.html" %}
>>>>>>> 3216e2ba5729a6379c419587e372836d36f4e675

repo_name: coMakeIT-TIC.github.io
repo_url: https://github.com/coMakeIT-TIC/coMakeIT-TIC.github.io
plugins:
  - search
  - mkdocs-video:
        is_video: True
        video_muted: True
        video_controls: True
        css_style:
        width: "800%"

markdown_extensions:
  - attr_list
<<<<<<< HEAD
=======

>>>>>>> 3216e2ba5729a6379c419587e372836d36f4e675
copyright: |
  &copy; 2023 <a href="https://github.com/coMakeIT-TIC/coMakeIT-TIC.github.io"  target="_blank" rel="noopener">TIC@CoMakeIT</a>